### PR TITLE
bowl and flywheel examples

### PR DESCRIPTION
**Pull request by zignig**
Two more examples, general exploration.

### CODE REVIEW

**Comment by bschwind** [comment]
Nice! I'll try these out. Do note that the modeling API is subject to change, especially for boolean subtraction (see #107 for an example) and workplane manipulation. If this gets merged first I'll be happy to update them to whatever is most idiomatic at the time, though.

**Comment by bschwind** [comment]
Also it's not at all obvious, but I don't intend for many people to create models with this crate directly, the compilation times are terrible.

I want to make a lightweight modeling API that compiles to WASM, which gets loaded by a viewer binary and executed. So you'll get live-updating renders as you code, compilation times are fast, and everyone is happy.

The modeling API will likely look very similar or identical to what I have now though, depending on how the WASM stuff goes.

**Comment by bschwind** [comment]
Ooh, cool flywheel!

Screen Shot 2023-07-24 at 10 48 28 PM

**Comment by bschwind** [comment]
By the way, I'm going to run the CI workflows but it'll probably ding you for formatting.

You can run `cargo +nightly fmt` to fix it.

I wish `rustfmt` had this option (there's an [open PR](https://github.com/rust-lang/rustfmt/pull/5834)), but I prefer trailing zeroes on float literals (`0.` -> `0.0`). Sorry for being pedantic, it should already be in `rustfmt` to be honest.

**Comment by zignig** [comment]
coolies.

I will start a repo o stuff and update it as required. This looks like a cool thing.

SGK.

**Comment by bschwind** [comment]
@zignig I'm not sure I have permission to push to your fork's branch. I rebased your branch on the latest `main`, you can see the changes I made here:

https://github.com/bschwind/opencascade-rs/compare/bowl-flywheel-rebase?expand=1

[This particular commit](https://github.com/bschwind/opencascade-rs/commit/6be9e5133fd82f239c11c4e4c591594171cbaeca)

**Comment by zignig** [comment]
With some changes with the api, I'll rewrite them anyway. Close this pull and I will make a new one.

**Comment by bschwind** [comment]
@zignig it's been awhile since I've put focused work into this project, but I'll happily add your examples to the main repo if you'd like to update them to the current modeling API.

**Pull request closed without merging**
