### PR TITLE
Add iges import and export

### PR DESCRIPTION
**Pull request by fidoriel**
closes https://github.com/bschwind/opencascade-rs/issues/184

### CODE REVIEW

**Comment by fidoriel** [comment]
@bschwind ping :)

**Comment by fidoriel** [comment]
For some reason, I messed up the history and did not commit the read and write functions, the heart of this PR. Now I added them.

**Comment by bschwind** [comment]
@fidoriel got it, no worries!

**Review by bschwind — APPROVED** [review]
Sorry for the huge delay, LGTM! December has been a super busy month.

There are some functions that don't need to be added to `wrapper.hxx`, but that's minor and I can clean that up later. I'm in the middle of refactoring code related to that file anyway.

**Pull request merged**
